import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Widget from '../components/Widget'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { ThemeProvider } from '@/components/theme-provider'
import {
  TextSizeContext,
  TextSizeProvider
} from '@/components/textSize-provider'
import { useContext } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Essential Fitness',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <TextSizeProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            disableTransitionOnChange
            enableSystem
          >
            <Navbar />
            {children}
            <Widget />
            <Footer />
          </ThemeProvider>
        </TextSizeProvider>
      </body>
    </html>
  )
}
